version: 2.1
jobs:
  build:
    docker:
      - image: docker:latest
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t my-image .
      - save_cache:
          key: v1-docker-{{ checksum "Dockerfile" }}
          paths:
            - /usr/local/bin/docker/
            - /root/.docker/
  deploy:
    docker:
      - image: flyio/flyctl:latest
    steps:
      - checkout
      - run:
          name: Install Flyctl
          command: |
            curl -L https://fly.io/install.sh | sh
      - run:
          name: Login to Fly.io
          command: |
            flyctl auth login --access-token fo1_h6VXJ_7EvxElGt01Bk4B9kRmFuMRYjQ_bkQCXhu_0WY
      - run:
          name: Deploy Docker image to Fly.io
          command: |
            flyctl deploy --image my-image --app retina-dd
